### ISSUE TITLE
Do not use credentials as parameters

### ISSUE THREAD

**Issue by sebnaf** [WoodWing/ww-assets-postman-collection#2]
Do not use credentials as parameters, use them in the body instead to not end up in e.g. ALB logs.

**Comment by Gappster** [comment]
Having a problem doing this. For some reason the login call is not passing the credentials when I set the body to: 

{
    "username":"xxx",
    "password":"yyy"
}

Need to figure out why...

**Comment by tistre** [comment]
Here’s a pull request for moving to body form-data – works fine for me:
https://github.com/WoodWing/ww-assets-postman-collection/pull/8
