### ISSUE TITLE
https://{{assetsUrl}}/services/apilogin

### ISSUE THREAD

**Issue by sebnaf** [WoodWing/ww-assets-postman-collection#3]
Store the received authToken in a postman variable to get easily reused in consecutive calls.

**Comment by Gappster** [comment]
I've done this now with a variety of the variables. Will document and include in the ReadMe.

**Comment by tistre** [comment]
Here’s a pull request for reusing the authToken:
https://github.com/WoodWing/ww-assets-postman-collection/pull/7
