### ISSUE TITLE
Remove "Logout use with 'api'"

### ISSUE THREAD

**Issue by sebnaf** [WoodWing/ww-assets-postman-collection#4]
Remove "Logout use with 'api'" as you cannot use /services/logout on API sessions (/services/apilogin).

**Comment by Gappster** [comment]
Thanks for the comment! 

I'm able to Login with 'apilogin' and in the 'logout' call pass the authToken as a 'Cookie' in the variable. This logs the API user off. Let me know if your experience differs and I'll investigate.

**Comment by Gappster** [comment]
Hey there,

I checked on this with our developers. The 'apologin' call does work to logoff the 'api' user. However, best practice is to continue to reuse the session and when it expires, create a new session and continue on. So.. no need to use 'logoff'. I'm going to close this comment but feel free to re-open if needed.
